apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-estate
spec:
  selector:
    matchLabels:
      app: estateapp
  replicas: 1
  template:
    metadata:
      labels:
        app: estateapp
    spec:
      containers:
        - name: estate
          image: mjlee39/woorizip:0.1.2
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: service-estate
spec:
  selector:
    app: estateapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9092
  type: NodePort
