apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-estate
spec:
  selector:
    matchLabels:
      app: estate
  replicas: 1
  template:
    metadata:
      labels:
        app: estate
    spec:
      containers:
        - name: estateapp
          image: 211125685751.dkr.ecr.ap-northeast-2.amazonaws.com/woorizip-estate:20240504073458
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: service-estate
spec:
  selector:
    app: estate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9092
  type: NodePort
